#!/bin/bash

rm -r /var/lib/tomcat10/webapps/dc || true
mv /tmp/dc.war /var/lib/tomcat10/webapps/dc.war

chown tomcat:tomcat /var/lib/tomcat10/webapps/dc.war
deb-systemd-invoke enable tomcat10.service
deb-systemd-invoke start tomcat10.service
