#!/bin/bash

mv /tmp/dc.war /var/lib/tomcat9/webapps/dc.war
rm -r /var/lib/tomcat9/webapps/dc || true

chown tomcat:tomcat /var/lib/tomcat9/webapps/dc.war
deb-systemd-invoke enable tomcat9.service
deb-systemd-invoke start tomcat9.service
